version: '3'
services:
  db:
    image: mariadb:10.5.6
    environment:
      MYSQL_DATABASE: grupo3
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - 3306:3306
    volumes:
     - ./data/:/var/lib/mysql/
     - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8081:80
    links:
      - db
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    network_mode: host
